language: ruby

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3

gemfile:
  - gemfiles/Gemfile.activerecord-4.2.x
  - gemfiles/Gemfile.activerecord-5.0.x
  - gemfiles/Gemfile.activerecord-6.0.x

sudo: false

env:
  - DB_ADAPTER=mysql2
  - DB_ADAPTER=postgresql

before_script:
  - mysql -e 'create database activerecord_json_validator_test;'
  - psql -c 'create database activerecord_json_validator_test;' -U postgres

script:
  - 'echo "Checking code style" && bundle exec phare'
  - 'echo "Running tests" && bundle exec rake spec'

addons:
  postgresql: 9.3
